my.data.sid=10
my.data.sname=rahul
my.data.sfee=3.3
my.data.prjs[0]=p1
my.data.prjs[1]=p2
my.data.prjs[2]=p3
my.data.prjs[3]=p4
my.data.dept.code=c1
my.data.dept.adm=AJ
my.data.dept.mode=Active
debug=true